<?php

namespace App\Models;

use App\Core\Model;


class User extends Model
{
    protected ?int $id = 0;
    protected ?string $login = "";
    protected ?string $password = "";

    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int|null $id
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string|null
     */
    public function getLogin(): ?string
    {
        return $this->login;
    }

    /**
     * @param string|null $login
     */
    public function setLogin(?string $login): void
    {
        $this->login = $login;
    }

    /**
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @param string|null $password
     */
    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    public function getRecipeCount() {
        if (!$this->getId()) {
            return [];
        }
        return Recipe::getAll("recipe_id = ? ",[$this]);
    }
}